name: Build and Upload Fonts # 工作流的名称

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 操作系统上运行此作业

    steps:
    - name: Checkout code # 步骤名称：检出仓库代码
      uses: actions/checkout@v4 # 使用 actions/checkout@v4 Action 来检出代码

    - name: Make scripts executable # 步骤名称：赋予脚本执行权限
      run: |
        chmod +x ttf/1.sh
        chmod +x shell/2.sh # 确保 1.sh 和 2.sh 脚本有执行权限

    - name: Execute 1.sh # 步骤名称：执行 1.sh 脚本
      run: ttf/1.sh # 执行仓库根目录下的 1.sh 脚本

    - name: Execute 2.sh # 步骤名称：执行 2.sh 脚本
      run: shell/2.sh # 执行仓库根目录下的 2.sh 脚本

    - name: Upload font artifacts # 步骤名称：保存成品文件
      uses: actions/upload-artifact@v4 # 使用 actions/upload-artifact@v4 Action 来上传文件作为工作流的成品
      with:
        name: built-fonts # 成品的名称，您可以在工作流运行后下载这个成品
        path: | # 指定要上传的文件路径
          myfont.ttf
          myfont.otf
          retention-days: 1 # 可选：设置成品保留天数，默认为 GitHub 的默认设置
